### PR TITLE
Updated css for link preview image

### PR DESCRIPTION
**Pull request by MayankPriy**
### What do you want to achieve?
-
the issue was that the image preview in the link was not clearly visible for the logo

Screenshot 2023-05-15 at 12 21 43 PM

it should be clear like this, so fixed it 

Screenshot 2023-05-15 at 12 24 03 PM

### Screenshot
- 

NOTE: Make sure you're comparing your branch with the correct base branch

### CODE REVIEW

**Comment by devashishmamgain** [comment]
@MayankPriy what is this task for?

**Comment by MayankPriy** [comment]
@devashishmamgain  I have updated the details in PR

**Comment by devashishmamgain** [comment]
> @devashishmamgain I have updated the details in PR

good, but why it requires review from me specially?

**Comment by MayankPriy** [comment]
I think it came automatic

**Comment by Sanjeevsinghnegi** [comment]
@MayankPriy please update the PR Form

Screenshot 2023-05-14 at 10 18 57 PM

**Comment by MayankPriy** [comment]
@PoojaGC  please test

**Comment by MayankPriy** [comment]
@anujpanwar01  @Sanjeevsinghnegi  please check

**Review by panwaranuj01 — APPROVED** [review]

**Pull request merged**
