### PR TITLE
Added test Quick replies

### PR DESCRIPTION
**Pull request by archit2602**
### What do you want to achieve?
- Testing quick replies

### PR Checklist

- [ ] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

- navigate to `cd playwright_test/`
- run `npx playwright test`

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

### CODE REVIEW

**Review by devashishmamgain — DISMISSED** [review]

**Review by devashishmamgain — APPROVED** [review]

**Comment by vipinkom1** [comment]
@archit2602   please check this not working in firefox.

Screenshot 2023-02-13 at 10 01 04 AM

Screenshot 2023-02-13 at 9 54 33 AM

**Comment by archit2602** [comment]
> @archit2602 please check this not working in firefox.
> 
> Screenshot 2023-02-13 at 10 01 04 AM
> 
> Screenshot 2023-02-13 at 9 54 33 AM

Retry once because this is working fine in my device also might be slow internet issue @vipinkom1

**Comment by vipinkom1** [comment]
@archit2602  I tried it is not working on my device

**Comment by vipinkom1** [comment]
let me know if you need any thing from my side.

**Review by vipinkom1 — APPROVED** [review]

**Pull request merged**
